# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst » https://flurinduerst.ch
# URL: https://github.com/flurinduerst/WPDistillery
#
# For detailed instructions on this file read the config.yml-documentation at
# https://github.com/flurinduerst/WPDistillery/blob/master/README_CONFIG.md
#
# File Version: 1.5.1


# INSTALLATION
#################################################################

# WordPress folder
wpfolder: www

# language/timezone
wplocale: en_AU
timezone: "Australia/Adelaide"

# admin user settings
admin:
  user: drawcard
  password: admin
  email: admin@drawcard.com.au

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: 192.168.33.10/clients/client-name/www/ # Edit this
  title: Client Name # Edit this
  description: Client Description # Edit this
  permalink_structure: "/%year%/%monthnum%/%day%/%postname%/"
  thumbnail_width: 400
  thumbnail_height: 400
  medium_width: 700
  medium_height: 700
  large_width: 1200
  large_height: 1200
  # use page as frontpage
  page_on_front: true
    frontpage_name: Homepage
  # automatic converttion of smilies
  convert_smilies: true

# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: Sage
  rename: "drawcard-theme"
  url: "https://github.com/roots/sage/archive/master.zip" # Update this to drawcard's sage v9 branch when ready
  # add branch (e.g. master) or leave empty ("") if theme is not downloaded from a git repository
  source_branch: master

# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - duplicate-post
  - enable-media-replace
  - simple-page-ordering
  - user-switching
  - autodescription #The SEO Framework Plugin
  - font-awesome-shortcodes
  - tinymce-advanced
  - contact-form-7
  - bwp-recaptcha
  - coming-soon
  - "https://github.com/roots/roots-wrapper-toolbar/archive/sagesupport.zip" # Sage Theme Toolbar
  - "https://github.com/afragen/github-updater/archive/master.zip"
  - "https://github.com/wp-sync-db/wp-sync-db/archive/master.zip"
  - "https://github.com/wp-sync-db/wp-sync-db-media-files/archive/master.zip"
  - "https://github.com/wp-sync-db/wp-sync-db-cli/archive/master.zip"
  - "https://github.com/wp-sync-db/wp-sync-db-multisite-tools/archive/delicious-brains.zip" #Update this to master branch when available

# plugins to install BUT leave deactivated
plugins_inactive:
  - pods
  - elementor
  - wordfence
  - wp-super-cache
  - adminimize
  - regenerate-thumbnails
  - admin-menu-editor
  - admin-menu-reorder
  - fakerpress


# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: true
